apiVersion: v1
kind: Service
metadata:
  name: service-flask-app
  namespace: initial-laura-diaz
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000
