# The docker-compose.yml files are versioned, which means it is very important to specify the version of the instructions we want to give.
version: "3.9"

# nginx server
services:
  web:
    image: nginx:alpine
    # Port 8080
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  # php-fpm configuration
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
