apiVersion: v1
kind: Pod
metadata:
  name: wanderlust-frontend-pod
  labels:
    name: wanderlust
spec:
  containers:
    - name: wanderlustfront
      image: lauradiazdev/wandelust:frontend-1.2.0
      env:
        - name: VITE_API_PATH
          value: "http://localhost:5000"
      resources:
        limits:
          memory: "128Mi"
          cpu: "300m"
      ports:
        - containerPort: 80
          protocol: TCP
          name: http-port
