name: CI/CD Pipeline
on:
  workflow_dispatch:
  push: 
    branches: [main]
env:
  REGISTRY: lauradiazdev
  REPOSITORY: wanderlust
  VERSION: v1
jobs:
  ci-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kubernetes/wanderlust-challenge_01/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "21"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
        continue-on-error: true
  cd-frontend:
    runs-on: ubuntu-latest
    needs: [ci-frontend, cd-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker Login 
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Docker Build
        run: |
          cd kubernetes/wanderlust-challenge_01/frontend
          docker build -t $REGISTRY/$REPOSITORY:frontend-$VERSION .
          docker push $REGISTRY/$REPOSITORY:frontend-$VERSION
    
  ci-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kubernetes/wanderlust-challenge_01/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "21"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
        continue-on-error: true
        
  cd-backend:
    runs-on: ubuntu-latest
    needs: [ci-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker Login 
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Docker Build
        run: |
          cd kubernetes/wanderlust-challenge_01/backend
          docker build -t $REGISTRY/$REPOSITORY:backend-$VERSION .
          docker push $REGISTRY/$REPOSITORY:backend-$VERSION
    
