name: CI/CD Pipeline
on:
  workflow_dispatch:
  push: 
    branches: [main]
jobs:
  ci-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "21"
      - name: Install dependencies
        run: |
          cd kubernetes/wanderlust-challenge_01/frontend
          npm install
      - name: Run tests
        run: |
          cd kubernetes/wanderlust-challenge_01/frontend
          npm run test
        continue-on-error: true
  cd-frontend:
    runs-on: ubuntu-latest
    needs: [ci-frontend, ci-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker Login 
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     

  ci-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "21"
      - name: Install dependencies
        run: |
          cd kubernetes/wanderlust-challenge_01/backend 
          npm install
      - name: Run tests
        run: |
          cd kubernetes/wanderlust-challenge_01/frontend
          npm run test
        continue-on-error: true
        
  cd-backend:
    runs-on: ubuntu-latest
    needs: [ci-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker Login 
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
