name: CI/CD Pipeline
on:
  push:
    branches: [main]
jobs:
  ci-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "21"
      - name: Install dependencies
        run: |
          cd kubernetes/wanderlust-challenge_01/frontend
          npm install

  ci-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "21"
      - name: Install dependencies
        run: |
          cd kubernetes/wanderlust-challenge_01/backend 
          npm install
